### ISSUE TITLE
Compatibility with Vapoursynth R45 R46 R47

### ISSUE THREAD

**Issue by 2014BDuck** [lordmulder/Simple-x264-Launcher#19]
![Screenshot from 2019-08-06 09-50-56](https://user-images.githubusercontent.com/30280396/62505552-b4ee4a80-b82f-11e9-9339-369e08a6d80b.png)

When using Vapoursynth **R46 + Python3.7 on windows 10**, it said I have to clean up vapoursynth plugins folder bla bla bla (Vapoursynth is newly installed whose plugins folder should be clean).

I have to click "ignore", and run the encode process, it said: no vapoursynth installed, sure to continue bla bla bla? click "yes", and then encode failed.

Then I tried manually use command line to run like(Which work correctly):
![Screenshot from 2019-08-06 09-49-45](https://user-images.githubusercontent.com/30280396/62505509-92f4c800-b82f-11e9-81cf-925462b468ec.png)

It appeared on both my local PC and remote windows server. I believe it's because launcher is not compatible with latest Vapoursynth. R47 is out as well. Please confirm it's Compatibility. It's still not usable for R46 right now.

**Comment by lordmulder** [comment]
Hello.

VapourSynth R46 changed a lot of things! In the latest release of Simple x264 Launcher (v2.92) the VapourSynth detection code has been adjusted for the changes in VapourSynth. As a result, the *minimum* supported VapourSynth version is now R46 – older versions are **not** supported anymore.

Unfortunately, a small regression in Simple x264 Launcher v2.92 is causing a wrong "critical error" message, when VapourSynth is **not** found at all. So, be sure to install the Hotfix from here:
[`x264_launcher.2019-07-22.hotfix-1.zip`](https://github.com/lordmulder/Simple-x264-Launcher/files/3419047/x264_launcher.2019-07-22.hotfix-1.zip)

If, after that, you still have problem, please launch **`x264_launcher.exe`** with the extra command-line option **`--console`** in order to enable the Debug console. Then post the output...

Regards.

**Comment by lordmulder** [comment]
...or see new release here:
https://github.com/lordmulder/Simple-x264-Launcher/releases/tag/v2.93

**Comment by 2014BDuck** [comment]
Sure. Will test it tonight. Thanks for your reply and efforts.
