### ISSUE TITLE
Windows Server 2012 launch error starts from version 2.90 inclusively

### ISSUE THREAD

**Issue by neovad** [lordmulder/Simple-x264-Launcher#23]
Error message: "Executable 'x264_launcher.exe' requires Windows 8.1 and later"

**Comment by ted423** [comment]
server 2012 seems like vista?

**Comment by ted423** [comment]
Means you need server 2016 and later

**Comment by lordmulder** [comment]
“Windows 8.0” and the corresponding _server_ edition, “Windows Server 2012”, in fact are **Windows NT 6.2**.

Accordingly, “Windows 8.1” and “Windows Server 2012 R2” are **Windows NT 6.3**.

You get the error message on “Windows 8.0”, and likewise on “Windows Server 2012”, because it's technically the same OS.
