### ISSUE TITLE
Use 64-bit VapourSynth on 64-bit systems?

### ISSUE THREAD

**Issue by HuBandiT** [lordmulder/Simple-x264-Launcher#3]
Greetings,

Background:
----

I am on Win7 64-bit, developing a 64-bit filter under 64-bit VapourSynth, referencing 64-bit dlls for everything (ffms2, fmtconv, etc.), VapourSynth Editor 64-bit runs my .vpy (which includes my filter) with no problems.

Now I wanted to do a test encode with x264, so I fired up Simple x264 Launcher, specified my .vpy script as input, specified x264 64-bit as encoder, and attempted to encode.

Issue:
----

Simple x264 Launcher invoked my .vpy script under 32-bit VapourSynth to get info on my clip, which failed, since the 64-bit plugins specified in the script failed to load under 32-bit VapourSynth.

When attempting to remedy this, I have found a setting to explicitly specify to use 64-bit AviSynth, but I have not found a setting to explicitly specify to use 64-bit VapourSynth.

Requested change:
----

Please enable Simple x264 Launcher to use 64-bit VapourSynth for encoding.

Thank you in advance.

**Comment by lordmulder** [comment]
I have improved VapourSynth detection code today, so 32-Bit and 64-Bit versions will now be detected separately:
0c6c00202e8d8b7ed577ea8648facaa9b2f60ecc

**Comment by lordmulder** [comment]
**Here is a new test build:**
http://sourceforge.net/projects/muldersoft/files/Simple%20x264%20Launcher/Testing/x264_launcher.2015-02-28.exe/download

**Comment by HuBandiT** [comment]
Works for me! :+1:

**Comment by HuBandiT** [comment]
Thank you, started using it, this is great!

**Comment by d4k0** [comment]
I still can't get this to work.

If I install Python 3.5.1 x86 and VapourSynth x86, Simple x264 Launcher recognizes VapourSynth.

If I install Python 3.5.1 x64 and VapourSynth x64 (withouth the 32-bit versions), Simple x264 Launcher can't find VapourSynth and displays an error message. Setting "Prefer 64-Bit source [...]" also doesn't help. StaxRip for example finds the 64-bit version without a problem. I also tried to install both programs to a different directory, but that also didn't help.

What could be the problem? I'm using Simple x264/x265 Launcher v2.66 and Windows 10 x64.

**Comment by lordmulder** [comment]
> What could be the problem? I'm using Simple x264/x265 Launcher v2.66, VapourSynth R31 and Windows 10 x64.

What does the log say?

    x264_launcher.exe --console

---

> Setting "Prefer 64-Bit source [...]" also doesn't help.

The only thing that this option does it: Give preference to 64-Bit VapourSynth/Avisynth (instead of 32-Bit one), *if and only if both variants (32-Bit and 64-Bit) are installed.*

**Comment by lordmulder** [comment]
> What could be the problem? I'm using Simple x264/x265 Launcher v2.66, VapourSynth R31 and Windows 10 x64.

What does the log say?

    x264_launcher.exe --console

---

> Setting "Prefer 64-Bit source [...]" also doesn't help.

The only thing that this option does it: It gives preference to 64-Bit VapourSynth/Avisynth (instead of 32-Bit one), *if and only if both variants (32-Bit and 64-Bit) are installed.*

---

Just now I installed 32-Bit *and* 64-Bit Python on my system (BTW: the Python web-site makes it surprisingly difficult to find the 64-Bit download!) and then VaporSynth. The VaporSynth installer offered to install 32-Bit and 64-Bit version. I installed both.

Simple x264 Launcher recognizes them just fine:

    [Check for VapourSynth support]
    VapourSynth thread has been created, please wait...
    VapourSynth Dir: C:/Program Files (x86)/VapourSynth
    VapourSynth EXE: C:/Program Files (x86)/VapourSynth/core32/vspipe.exe
    VapourSynth DLL: C:/Program Files (x86)/VapourSynth/core32/vapoursynth.dll
    VapourSynth version was detected successfully.
    VapourSynth 32-Bit edition found!
    VapourSynth EXE: C:/Program Files (x86)/VapourSynth/core64/vspipe.exe
    VapourSynth DLL: C:/Program Files (x86)/VapourSynth/core64/vapoursynth.dll
    VapourSynth version was detected successfully.
    VapourSynth 64-Bit edition found!
    VapourSynth thread finished.
    VapourSynth support is officially enabled now! [x86=1, x64=1]

**Comment by d4k0** [comment]
I just made some tests, here are the results:

Only Python 64-bit and VapourSynth 64-bit are installed:

![Python 64-bit and VapourSynth 64-bit](http://i.imgur.com/OAbWawZ.png)

Only Python 32-bit and VapourSynth 32-bit are installed:

![Python 32-bit and VapourSynth 32-bit](http://i.imgur.com/iV0HCGk.png)

Both versions of both programs are installed:

![Both versions of both programs are installed](http://i.imgur.com/Opqmhvt.png)

So Simple x264 Launcher somehow only recognizes the 64-bit version when the 32-bit version is also installed. Is this the intended behaviour?

**Comment by lordmulder** [comment]
> So Simple x264 Launcher somehow only recognizes the 64-bit version when the 32-bit version is also installed. Is this the intended behaviour?

Nope.

However your screenshots seem contradictory. The screenshot that says *"Only Python 32-bit and VapourSynth 32-bit are installed"* clearly shows that the 32-Bit **and** 64-Bit version have been found. It even shows the path to the 32-Bit VapourSynth EXE/DLL **and** the path to the 64-Bit VapourSynth EXE/DLL that existed at that time. If 64-Bit VapourSynth was really was **not** installed, how can the 64-Bit binaries be found? Are you saying Simple x264 Launcher did print out a path to VapourSynth EXE/DLL that did **not** exist in fact? Did you verify that ???

**Comment by d4k0** [comment]
I also noticed this. That's why I retested it and made sure that there are no leftovers of VapourSynth (I also did this before). Nevertheless, Simple x264 Launcher still lists these files even though they don't exist:

![Files don't exist](http://i.imgur.com/ZT0GktE.png)

**Comment by lordmulder** [comment]
Okay, I think I misread your log :sleeping:

Actually the *"Only Python 32-bit and VapourSynth 32-bit are installed"* screenshot shows the path where the 64-Bit version would be expected, but then it says "**not** found". So that is just as expected.

However, this does **not** explain why your *"Only Python 64-bit and VapourSynth 64-bit are installed"* screenshot does **not** seem to find VapourSynth at all. This indicates that the Registry entries for VapourSynth were **not** found at all.

Can you check whether any of these Registry entries:
* Path
* InstallLocation
* Inno Setup: App Path

...exists in any of these Registry keys:
* HKLM\SOFTWARE\VapourSynth
* HKLM\Microsoft\Windows\CurrentVersion\Uninstall\VapourSynth_is1

?

**Comment by d4k0** [comment]
Just out of curiosity I created the path entry manually at `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VapourSynth` and Simple x264 Launcher now recognizes VapourSynth x64:

![HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VapourSynth](http://i.imgur.com/Sod0x4p.png)

So Simple x264 Launcher indeed seems to only look at `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VapourSynth` for finding the path. This works if both the 32-bit and 64-bit of VapourSynth are installed (as the 32-bit version creates the path entry at this location), but when only the 64-bit version is installed this doesn't work because it only creates the path entry at `HKEY_LOCAL_MACHINE\SOFTWARE\VapourSynth`.

**Comment by lordmulder** [comment]
That's a Windows "feature": If a **32-Bit** process running on **64-Bit** Windows tries to access `HKLM\SOFTWARE\foobar`, this is redirected *transparently* to `HKLM\SOFTWARE\foobar\WOW6432Node`.

Because Simple x264 Launcher is a 32-Bit program, it can only "see" the key `SOFTWARE\WOW6432Node\VapourSynth`, **not** `SOFTWARE\VapourSynth`. However, workaround is possible...

Please stay tuned :hourglass:

**Comment by lordmulder** [comment]
Please try this new **TEST** version:
https://sourceforge.net/projects/muldersoft/files/Simple%20x264%20Launcher/Testing/x264_launcher-TEST.2016-03-11.exe/download

**Comment by lordmulder** [comment]
No more replay, so I'll consider this one resolved.

**Comment by d4k0** [comment]
Sorry for the late reply, I was busy this week and forgot to answer. I can confirm that the detection works now with version 2.67. Thanks for the fix!

**Comment by hopehoney** [comment]
hi, i installed vapoursynth 64 bit on my windows x64, when i try to drag my video to the script it redirects me to my user in windows and I get the internal and external command error, try it with vapourx32 and i dont have this problem with the 64 one, I have tried to solve anyway, if you could tell me how to solve this I would be so grateful.

**Comment by lordmulder** [comment]
> when i try to drag my video to the script

I have no idea what that is supposed to mean...

> it redirects me to my user in windows and I get the internal and external command error

No idea what this could mean either 😕
